apiVersion: apps/v1
kind: Deployment
metadata:
  name: her
spec:
  replicas: 1
  selector:
    matchLabels:
      app: her
  template:
    metadata:
      labels:
        app: her
    spec:
      containers:
      - image: okteto.dev/her:latest
        name: her
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6086d426-5ab1-4cda-8e17-6ddf56bc2c9a"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "24c89a44-9a40-41b9-a972-6dd09f9fdbd9"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
